### ISSUE TITLE
small demo UI updates

### ISSUE THREAD

**Issue by patudom** [cosmicds/tempods#13]
Can we please:

- [x] start the power plant selections with the default being every layer turned off? (It's better to start with less and add more as the user gets used to the interface rather than starting with every possible option visible).  (@Carifio24?)
- [x] In #12, I updated the y-axis to have a bit of padding so the viewer doesn't top out at the same value as y_max, but I couldn't figure out how to add this y-axis padding to subsets.  (@jfoster17?)
- [x] When I delete a subset, it disappears from the time viewer, but it is still displayed in the map viewer even though the subset has been deleted. Can we make sure the subset box on the map is also deleted? (@jfoster17?)

Thank you!

**Comment by jfoster17** [comment]
I did items 2 and 3 in the latest version of glue-map, so https://github.com/jfoster17/glue-map/commit/623d76ae8b21d4020f8bd465412fffea65af9fed and https://github.com/jfoster17/glue-map/commit/a62174a83d8aa74937d753df245a4f059c5d0144

Not quite sure how to do the power plant selection thing.
